#!/bin/bash

begin=$(date +%s%N)
for ((i = 0; i < 500; i++))
do
	taskset -c 1 ./NN &
#	ps -o stime,etime $!
done

wait
end=$(date +%s%N)
spend=$(expr $end - $begin)
spend=$(expr $spend / 1000000)
echo "total time: $spend ms"

#echo "$$"
#while true; do
#	p=$(ps -o ppid=$$)
#	echo "$p"
#	if [ "$p" == "" ]; then 
#		end=$(date +%s)
#		break
#	else
#		sleep 1
#	fi
#done
